### ISSUE TITLE
MacOS and Windows Compatibility 

### ISSUE THREAD

**Issue by sombek** [haxzie/slidex#16]
When I want to use the app on macOS it's not responding to any good signs just runs the jar file then stops.
I tried to run this code snippet from `node-key-sender` Docs.
```
      keySender.startBatch()
          .batchTypeKey('N', 1000)
          .batchTypeKey('o', 1000)
          .batchTypeKey('d', 1000)
          .batchTypeKey('e', 1000)
          .sendBatch();
```
It runs only after I click on a text field to be able to type the text. I think the problem is it's focksing on the jar file and since the jar file has nothing to do with text or the arrow 'left', 'right' ... etc 
it's not responding.

What is the experience on Windows? Is it fast enough?

-- *I didn't test it on the previous library*

**Comment by haxzie** [comment]
Facing the same issue on Windows too.

**Comment by haxzie** [comment]
@sombek The issue was with the node-key-sender library's jar file path. For some reason, they used single quotes to enclose the actual directory path of the JAR file in the command being executed. Removing the quotes fixed the issue in Windows 10, executing in the command prompt and WSL with ubuntu. Anyhow, we don't have enough privileges with the WSL to dispatch the keyPress to the Windows host.

Fixed it by overriding the library function to bring about the above-mentioned changes.
